### ISSUE TITLE
Wrong referer format handling

### ISSUE THREAD

**Issue by tomas-doudera** [simplestats-io/laravel-client#11]
Hello, 

we have some requests with **referer** format like **"www.google.com"** and there is problem with parser_url() in **CheckTracking(line 47)**. In cases when "https://" is not present in referer then parser does not return array with key "host" and it throws error.

**Some examples what parser returns:**

```
parse_url("https://google.com/test?v=2");
result: [
  "scheme" => "https",
  "host" => "google.com",
  "path" => "/test",
  "query" => "v=2",
]
```

```
parse_url("www.google.com");
result: [
  "path" => "www.google.com",
]
```

```
parse_url("google.com");
result: [
  "path" => "google.com",
]
```

```
parse_url("www.google.com/test?v=2");
result: [
  "path" => "www.google.com/test",
  "query" => "v=2",
]
```

**Solution would be something like this:**

```
$parsedUrl = parse_url($_SERVER['HTTP_REFERER']);
return $parsedUrl['host'] ?? $parsedUrl['path'] ?? '';
```

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/c4dcd542-9a01-467f-9909-73b0eb256d9f">

If you agree with the solution I can open PR for that or If I missing something please suggest how to handle this case.

Thank you in advance.

**Comment by Sairahcaz** [comment]
Hi @tomas-doudera, the solution looks good to me. A PR would be awesome!

**Comment by Sairahcaz** [comment]
@tomas-doudera could you also please make sure that for this kind of url we also only get the URL in the path. Else the referer would be with the path... Or maybe is it easier to check if the referer has a scheme if not, you could prepend "https://" and then pass it to parse_url?

```php
parse_url("www.google.com/test?v=2");
result: [
  "path" => "www.google.com/test",
  "query" => "v=2",
]
```

**Comment by tomas-doudera** [comment]
@Sairahcaz if you are ok with the case below we can prepend https.

Case when you prepend https but www. is present.

```
parse_url("https://www.google.com/test?v=2");
[
  "scheme" => "https",
  "host" => "www.google.com",
  "path" => "/test",
  "query" => "v=2",
]
```

**Comment by Sairahcaz** [comment]
@Sairahcaz looks good I'd say. Would be super cool if you could write a small unit test for that, with all theses cases...
